# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RCDemo_Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

platform :ios, '7.0'
pod 'RongCloudIM/IMLib', '~> 2.9.11'
pod 'RongCloudIM/IMKit', '~> 2.9.11'  


  # Pods for RCDemo_Swift

  target 'RCDemo_SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RCDemo_SwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
